permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# 作者信息
author: 
  name: Olive Zhao
  email: olivezhao@yeah.net
  link: 
  weibo: 
  github: http://github.com/lay1010
  music: 
  linkedin: 

# 站点信息
title: Olive的博客
description: My personal blog
url: http://olivezhao.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: olivezhao.github.io

# disqus 设置
disqus:
  shortname: OliveZhao

# 主题设置，自动激活某个标签
active: 滴答

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档